openapi: 3.0.3
info:
  title: PUCE Banner Data API
  version: "1.0.0"
  description: >
    Especificación OpenAPI para los servicios de lectura que alimentan la
    integración Zoho ↔ Banner. Incluye programas académicos, períodos y catálogos.
servers:
  - url: https://pucewsd.puce.edu.ec
paths:
  /banner/data/academicprograms:
    get:
      summary: Obtener programas académicos por campus
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de programas académicos
  /banner/data/academicperiods:
    get:
      summary: Listar períodos académicos
      responses:
        '200':
          description: Lista de períodos académicos
  /banner/data/getdata:
    get:
      summary: Obtener catálogos de referencia
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de elementos de catálogo